### ISSUE TITLE
Typo in the header navigation download button

### ISSUE THREAD

**Issue by davidyell** [PathOfBuildingCommunity/pathofbuildingcommunity.github.io#18]
![Screenshot 2024-12-17 at 15 38 45](https://github.com/user-attachments/assets/656f7d41-93d4-46dd-a582-52f6cddb4ccd)

Looks like a typo to me, as I would expect it to say 'Download'

Seems to be correct in `master` so perhaps just needs a re-deploy.

https://github.com/PathOfBuildingCommunity/pathofbuildingcommunity.github.io/blob/master/index.html#L16

**Comment by LocalIdentity** [comment]
The website you're looking at is some AI created shit that someone made to mislead people. Our actual website is this https://pathofbuilding.community/

**Comment by davidyell** [comment]
Ah, I was linked to https://pathofbuilding.net/ by a post on Arqade. Thanks for the update, I will pass on the info. 👍
