### ISSUE TITLE
Elemental Equilibrium doesn't seem to work properly (using Malachai's Artifice)

### ISSUE THREAD

**Issue by Blitzillagaming** [PathOfBuildingCommunity/pathofbuildingcommunity.github.io#5]
Equipping the ring reduces DoT DPS
https://pastebin.com/nwJQxtAT

**Comment by Regisle** [comment]
![image](https://user-images.githubusercontent.com/49933620/104588706-b2e11a00-56b8-11eb-9444-4ed9f514712c.png)

**Comment by Blitzillagaming** [comment]
Thanks.
