### ISSUE TITLE
Ahead by counter not valid anymore

### ISSUE THREAD

**Issue by zao** [PathOfBuildingCommunity/pathofbuildingcommunity.github.io#6]
The "Ahead by" counter on the website now says "undefined changes", probably when we detached from Openarl 

https://github.com/PathOfBuildingCommunity/pathofbuildingcommunity.github.io/blob/c470ad0ade7e771538785b59e1f6e1ba576bf516/index.html#L102-L108

![image](https://user-images.githubusercontent.com/260218/111645915-7b4e3580-8801-11eb-909e-454e19969383.png)

**Comment by ppoelzl** [comment]
Fixed.
